[package]
name = "transaction"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_bytes = "0.11.19"
serde.workspace = true
serde_json = "1.0.145"
bincode.workspace = true
anyhow.workspace = true
tiny-keccak = { version = "2.0", features = ["sha3"] }
tokio.workspace = true
kanal = "0.1.1"
